// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureBank.Database;

#nullable disable

namespace SecureBank.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240114165546_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("SecureBank.Database.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte>("LoginFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TemporaryPassword")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SecureBank.Database.AccountPassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftSalt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("BLOB");

                    b.Property<string>("RightSalt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountPasswords");
                });

            modelBuilder.Entity("SecureBank.Database.AccountPasswordIndex", b =>
                {
                    b.Property<long>("AccountPasswordId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Index")
                        .HasColumnType("INTEGER");

                    b.HasIndex("AccountPasswordId");

                    b.ToTable("AccountPasswordIndexes");
                });

            modelBuilder.Entity("SecureBank.Database.AccountPassword", b =>
                {
                    b.HasOne("SecureBank.Database.Account", "Account")
                        .WithMany("AccountPasswords")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SecureBank.Database.AccountPasswordIndex", b =>
                {
                    b.HasOne("SecureBank.Database.AccountPassword", "AccountPassword")
                        .WithMany()
                        .HasForeignKey("AccountPasswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountPassword");
                });

            modelBuilder.Entity("SecureBank.Database.Account", b =>
                {
                    b.Navigation("AccountPasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
